source 'https://www.rubygems.org'

gem 'rspec',              '2.14.1'
gem 'rspec-expectations', '2.14.5'
gem 'appium_lib',         '7.0.0'
gem 'rest-client',        '1.6.8'
gem 'cucumber',           '2.0.0'
gem 'spec',               '5.3.4'
gem 'sauce_whisk',        '0.0.13'
gem 'json',                '1.8.2'
gem 'chunky_png',          '1.3.4'
